services:
  - docker

env:
  - DOCKERFILE="debian/Dockerfile" TAG_PREFIX="debian"
  - DOCKERFILE="Dockerfile" TAG_PREFIX=""

before_script:
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - docker build -f $DOCKERFILE --build-arg S6_ARCH=armhf -t oznu/s6-node:$TAG_PREFIX .
