language: bash

services:
  - docker

env:
  - S6_ARCH=amd64 DOCKERFILE="Dockerfile" TAG_SUFFIX="amd64"
  - S6_ARCH=armhf DOCKERFILE="Dockerfile" TAG_SUFFIX="armhf"
  - S6_ARCH=amd64 DOCKERFILE="debian/Dockerfile" TAG_SUFFIX="debian"
  - S6_ARCH=armhf DOCKERFILE="debian/Dockerfile" TAG_SUFFIX="debian-armhf"

before_script:
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - export TARGET_IMAGE_TAG=$(if [ "$TRAVIS_BRANCH" = "master" ]; then if [ "$TAG_SUFFIX" = "" ]; then echo "latest"; else echo "$TAG_SUFFIX"; fi; else if [ "$TAG_SUFFIX" = "" ]; then echo "$TRAVIS_BRANCH"; else echo "$TRAVIS_BRANCH-$TAG_SUFFIX"; fi; fi)

script:
  - docker build -f $DOCKERFILE --build-arg S6_ARCH=${S6_ARCH} -t $TARGET_IMAGE:$TARGET_IMAGE_TAG .
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker push $TARGET_IMAGE:$TARGET_IMAGE_TAG
