services:
  - docker

env:
  - S6_ARCH=amd64 DOCKERFILE="alpine/Dockerfile" TAG_SUFFIX=""
  - S6_ARCH=armhf DOCKERFILE="alpine/Dockerfile" TAG_SUFFIX="armhf"
  # - S6_ARCH=amd64 DOCKERFILE="debian/Dockerfile" TAG_SUFFIX="debian"
  # - S6_ARCH=armhf DOCKERFILE="debian/Dockerfile" TAG_SUFFIX="debian-armhf"

before_script:
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - export TAG_PREFIX=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then if [ "$TRAVIS_BRANCH" = "master" ]; then echo ""; else echo "$TRAVIS_BRANCH"; fi; else echo ""; fi)
  - export TAG_PREFIX=$(if [ "$TAG_PREFIX" == "" ] && [ "$TRAVIS_BRANCH" = "master" ]; then echo "latest"; fi)

script:
  - echo $TAG_PREFIX
  - docker build -f $DOCKERFILE --build-arg S6_ARCH=${S6_ARCH} -t oznu/s6-node:$TAG_PREFIX:$TAG_SUFFIX .
